import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="p-10 bg-sky-400">
        <h1 className="text-lg font-mono"><a href="/">News Headlines</a></h1>
      </div>
      <div className="px-10 pt-5 pb-20 bg-gray-200">
        {children}
      </div>
      </body>
    </html>
  );
}
