import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-4xl">
        <div className="md:flex">
          <div className="md:shrink-0">
            <div className="h-48 w-full object-cover md:h-full md:w-48">
            <h1 className="text-lg font-mono text-center mt-10"><a href="/">News Headlines</a></h1>
          </div>
            
          </div>
          <div className="p-8">
            <div className="uppercase tracking-wide text-sm text-indigo-500 font-semibold">Available Countries</div>
            <a href="#" className="block mt-1 text-lg leading-tight font-medium text-black hover:underline">View top 5 headlines</a>
            <div className="mt-2 text-slate-500">
            {children}
            </div>
          </div>
        </div>
      </div>
      </body>
    </html>
  );
}
